### PR TITLE
Fix about page in mobile

### PR DESCRIPTION
**Pull request by Sergioamjr**
I fixed the about page in mobile, until 768px and the post image between 768px and 1200px.
Please, let me know what do you think.

### CODE REVIEW

**Comment by hummusonrails** [comment]
Hey Sergio! It looks really nice, I like the formatting you created, it looks cleaner. I did notice though that at around 360x640 (Galaxy S5, etc.) the picture moves to block a big chunk of the text. As I size up through different schema (iPhone 6, iPad, etc.) the problem persists. It's definitely better but would you mind taking another look? Thank you!

**Comment by Sergioamjr** [comment]
Thank you, Ben, of course, I'll take a look on that even today.

**Comment by Sergioamjr** [comment]
Can you check now, please? Feel free to ask me any alteration

**Comment by hummusonrails** [comment]
Same issue, unfortunately! This one is a bit complicated. Perhaps, just make it remove the image as the screen size gets smaller? It probably is a good idea anyways as it takes up valuable screen real estate on small devices. So maybe just set it up `display: none` for smaller sizes?

**Comment by Sergioamjr** [comment]
It's a good idea, but I'd like to try one more time. Just to know, are you talking about this image, right? I can decrease the height of this element like this, what do you think?
print

**Comment by hummusonrails** [comment]
That might work also. Did you check to see how it looks in various screen sizes? Once the height is changed does that resolve the issue of covering up the text?

**Comment by Sergioamjr** [comment]
I set a fixed height to image until 1024px, independent from screen height. Seems that not will covering up any text. I'll push the alterations for you see.

**Comment by hummusonrails** [comment]
This is what happens now. 

screen shot 2017-10-25 at 12 08 47 pm

Getting closer though :)

**Comment by hummusonrails** [comment]
For now, I merged your changes (awesome job btw!) but added a `display: none` for the image at a a `max-width: 1024px`. If you want to play with it more, please do so. 👍

**Pull request merged**
